
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///E:/idea_workspace/configserver/src/main/resources/config/
          username: two
  application:
    name: zc-server
server:
  port: 10010
